In [1]:
import numpy as np

In [3]:
# 创建数组

# 使用list创建
LIST1 = [1, 2, 3, 4, 5]
np.array(LIST1)

array([1, 2, 3, 4, 5])

In [31]:
# 从头创建数组

SHAPE = tuple((3, 5))
NUM = 3.14
START = 0
END  = 20
JUMP = 2

X1 = np.zeros(SHAPE)
X2 = np.ones(SHAPE)
X3 = np.full(SHAPE, NUM)
X4 = np.arange(START, END, JUMP)
X5 = np.linspace(START, END, 5)
X6 = np.random.random(SHAPE)
X7 = np.random.normal(0, 1, SHAPE) # 0代表平均均值 1代表方差
X8 = np.random.randint(START, END, SHAPE)
X9 = np.eye(3)
X10 = np.empty(SHAPE)

print("X1:", X1)
print("X2:", X2)
print("X3:", X3)
print("X6:", X6)

X1: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
X2: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
X3: [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
X6: [[0.63883053 0.51625576 0.5720904  0.92755137 0.4643032 ]
 [0.17776644 0.53578845 0.30876451 0.57387445 0.2617832 ]
 [0.96471865 0.66429978 0.15124432 0.85818558 0.51924439]]


In [33]:
# 数组的属性

print(X1.shape)
print(X1.size)
print(X1.ndim)
print(X1.dtype)
print(X1.itemsize)
print(X1.nbytes)

(3, 5)
15
2
float64
8
120


In [40]:
# 一维数组

print(X4)
print(X4[0])
print(X4[-1])
print(X4[::-1])

[ 0  2  4  6  8 10 12 14 16 18]
0
18
[18 16 14 12 10  8  6  4  2  0]


In [48]:
# 多维数组
X11 = np.random.randint(0, 20, (3, 5))
print(X11)
print(X11[:2, :3])

X11_sub_copy = X11[:2, :2].copy()  #c创建数组的副本
print(X11_sub_copy)

[[16 13 14 17 15]
 [ 3  3  1 16  7]
 [15 16 17  6 12]]
[[16 13 14]
 [ 3  3  1]]
[[16 13]
 [ 3  3]]


In [56]:
# 数组的变形

X12  = np.array([1, 2, 3])
print(X12.reshape((3, 1)))
print(X12[np.newaxis, :])
print(X12[:, np.newaxis])

[[1]
 [2]
 [3]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [61]:
# 数组拼接

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x,y]))
z = [99, 99, 99]
print(np.concatenate([x, y, z]))
grid = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.concatenate([grid, grid]))    # 沿着第一个轴拼接
print(np.concatenate([grid, grid], axis=1)) # 沿着第二个轴拼接
  
print(np.vstack([x, grid]))   #垂直拼接 
print(np.hstack([x, grid]))   #水平拼接 

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [74]:
# 分裂
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])   #[3, 5]分裂位置记录
print(x1, x2, x3)

grid = np.arange(16).reshape((4, 4))
print("grid:", grid)
upper, lower = np.vsplit(grid, [2])
print("upper:", upper, "\n", "lower:", lower)
left, right = np.hsplit(grid, [2])
print("left:", left, "\n", "right:", right)

[1 2 3] [99 99] [3 2 1]
grid: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
upper: [[0 1 2 3]
 [4 5 6 7]] 
 lower: [[ 8  9 10 11]
 [12 13 14 15]]
left: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 right: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [90]:
# 计算

x = np.arange(4)
print("x     =", x)
print("x + 5 =", x+5)
print("x - 5 =", x-5)
print("x * 2 =", x*2)
print("x / 2 =", x/2)
print("x // 2=", x//2)

x = np.array([-2, -1, 0, 1, 2])   
print("abs(x) = ", np.abs(x))


theta = np.linspace(0, np.pi, 3)
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))


x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(10)=", np.log10(x))

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1", np.expm1(x))
print("log(1 + x)", np.log1p(x))

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2= [0 0 1 1]
abs(x) =  [2 1 0 1 2]
theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(10)= [0.         0.30103    0.60205999 1.        ]
exp(x) - 1 [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) [0.         0.0009995  0.00995033 0.09531018]


In [93]:
# 专用的通用函数

from scipy import special

x = [1, 5, 10]
print("gamma(x)    =", special.gamma(x))
print("ln|gamma(x) =", special.gammaln(x))
print("beta(x, 2)  =", special.beta(x, 2))

x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)   =", special.erf(x))
print("erfc(x)  =", special.erfc(x))
print("erfinv(x)=", special.erfinv(x))

gamma(x)    = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x) = [ 0.          3.17805383 12.80182748]
beta(x, 2)  = [0.5        0.03333333 0.00909091]
erf(x)   = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)  = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)= [0.         0.27246271 0.73286908        inf]


In [101]:
# 高级的通用函数的特性

# 指定输出
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)    #指出输出位置   节省内存
print(y)

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)



# 聚合
x = np.arange(1, 6)
print(np.add.reduce(x))
print(np.multiply.accumulate(x))


# 外积
x = np.arange(1, 6)
print(np.multiply.outer(x, x))

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
15
[  1   2   6  24 120]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [110]:
# 聚合：最小值、最大值和其他值

L = np.random.random(100)
print(np.sum(L))
print(np.min(L))
print(np.max(L))

M = np.random.random((3, 4))
print(M.sum())
print(M.min(axis=0))
print(M.max(axis=1))

49.79177960825381
0.0013149036490764932
0.9765358381416007
6.078484991580654
[0.43230463 0.19381156 0.22533182 0.172783  ]
[0.61288692 0.6769034  0.95974272]
